name: Training Pipeline

on:
  schedule:
    - cron: "0 5 * * 1" # Semanalmente às 5h UTC (2h Brasília) toda segunda-feira
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      # Secrets
      API_KEY_FOOTBALL_DATA: ${{ secrets.API_KEY_FOOTBALL_DATA }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      # Hardcoded (public)
      DAGSHUB_REPO_OWNER: igorkuivjogi
      DAGSHUB_REPO_NAME: chute-certo
      MLFLOW_TRACKING_USERNAME: igorkuivjogi

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Download latest data
        run: uv run python scripts/download_data.py --seasons 2023 2024 2025 2026

      - name: Train and register model
        run: uv run python scripts/pipeline.py
